/* Extra grammar quiz questions – format: [question, rightAnswer, [wrong1, wrong2, wrong3]] */
window.BAHASA_MORE = window.BAHASA_MORE || {};
Object.assign(window.BAHASA_MORE, {
G1: [
 ["___ tinggal di Penang. (She lives in Penang.)", "Dia", ["Kami", "Anda", "Mereka"]],
 ["___ belajar bahasa Melayu. (We – not including you – study Malay.)", "Kami", ["Kita", "Dia", "Mereka"]],
 ["Encik Ali, apa pekerjaan ___? (What is your job, Mr Ali? – formal)", "anda", ["aku", "dia", "kami"]],
 ["___ semua rakan sekelas. (We are all classmates – including you.)", "Kita", ["Mereka", "Dia", "Saya"]],
 ["Which word do you use with a very close friend for 'I'?", "aku", ["anda", "mereka", "kita"]],
 ["___ suka bermain bola. (They like playing ball.)", "Mereka", ["Kita", "Saya", "Anda"]],
 ["Does Malay 'dia' mean he or she?", "Both – he and she", ["Only he", "Only she", "Only they"]],
 ["Cikgu bertanya, 'Adakah ___ faham?' (Do you understand?)", "awak", ["dia", "kami", "mereka"]],
 ["Ali dan Aina ialah kawan saya. ___ tinggal dekat sini. (They live near here.)", "Mereka", ["Kami", "Kita", "Anda"]],
 ["Dia dan saya pergi ke pasar. ___ membeli sayur. (We – he and I – buy vegetables.)", "Kami", ["Mereka", "Dia", "Anda"]],
 ["Which pronoun means 'they'?", "mereka", ["kami", "kita", "dia"]],
 ["Which pronoun means 'we (including you)'?", "kita", ["kami", "mereka", "saya"]],
 ["Ibu di dapur. ___ sedang memasak. (She is cooking.)", "Dia", ["Kami", "Anda", "Kita"]],
 ["Selamat pagi, Puan. Apa khabar ___? (How are you? – formal)", "anda", ["aku", "dia", "kami"]],
 ["Adik dan ___ suka menonton filem. (My younger sibling and I like watching films.)", "saya", ["mereka", "anda", "dia"]],
 ["'Saya' is a ___ word for 'I'.", "polite and safe", ["rude", "only for animals", "only for teachers"]],
 ["Guru berkata, 'Kita mesti belajar.' Who must study?", "The teacher and the pupils", ["Only the pupils", "Only the teacher", "Nobody"]],
 ["Ali ialah abang saya. ___ berumur lima belas tahun. (He is fifteen.)", "Dia", ["Kami", "Mereka", "Kita"]],
 ["Does the Malay verb change for I, you, he or they?", "No, it stays the same", ["Yes, it adds -s", "Yes, it adds -ed", "Only for 'they'"]],
 ["Ibu bapa saya di rumah. ___ sedang menonton televisyen. (They are watching TV.)", "Mereka", ["Dia", "Anda", "Kami"]]
],
G2: [
 ["___ pensel saya. (This is my pencil.)", "Ini", ["Itu", "Ialah", "Dia"]],
 ["Buku ___ tebal. (That book is thick.)", "itu", ["ini", "ialah", "ada"]],
 ["Kakak saya ___ jurutera. (My sister is an engineer.)", "ialah", ["itu", "ini", "tidak"]],
 ["Which sentence means 'That cat is small.'?", "Kucing itu kecil.", ["Itu kucing kecil ialah.", "Kecil itu kucing ialah.", "Kucing ialah itu kecil."]],
 ["Which sentence means 'This is a school.'?", "Ini sebuah sekolah.", ["Sebuah sekolah ini itu.", "Ini ialah itu sekolah.", "Sekolah ialah ini itu."]],
 ["Rumah ___ besar. (This house is big.)", "ini", ["itu", "ialah", "ada"]],
 ["Ibu saya ___ guru. (My mother is a teacher.)", "ialah", ["ini", "itu", "ada"]],
 ["How do you say 'that house'?", "rumah itu", ["itu rumah ialah", "ialah rumah itu", "rumah ialah itu"]],
 ["Cuaca ___ sangat panas. (This weather is very hot.)", "ini", ["itu", "ialah", "bukan"]],
 ["We normally do NOT use 'ialah' before…", "an adjective (e.g. besar)", ["a noun", "a name", "a job"]],
 ["Ayah saya ___ tinggi. (My father is very tall.)", "sangat", ["ialah", "ini", "itu"]],
 ["Which is correct: 'Malaysia is a country.'?", "Malaysia ialah sebuah negara.", ["Malaysia sebuah ialah negara.", "Ialah Malaysia negara sebuah.", "Malaysia negara ialah sebuah itu."]],
 ["Kedai ___ menjual buku. (That shop sells books.)", "itu", ["ialah", "adalah", "bukan"]],
 ["'Ini bukan kucing saya.' means…", "This is not my cat.", ["That is my cat.", "This is my cat.", "That is not my cat."]],
 ["Anjing ___ sangat besar. (That dog is very big.)", "itu", ["ialah", "ini", "saya"]],
 ["Which word is used for something FAR from the speaker?", "itu", ["ini", "ialah", "ada"]],
 ["'This is my house' in Malay is…", "Ini rumah saya.", ["Ini ialah rumah saya itu.", "Rumah ini saya ialah.", "Saya rumah ini."]],
 ["Pen ___ mahal, tetapi pensel ___ murah. (This pen is expensive but that pencil is cheap.)", "ini … itu", ["itu … ini", "ini … ini", "ialah … itu"]],
 ["Dia ___ pemandu bas. (He is a bus driver.)", "ialah", ["itu", "ini", "tidak"]],
 ["Which word means 'this'?", "ini", ["itu", "ialah", "ada"]]
],
G3: [
 ["Saya ___ pergi ke sekolah hari ini. (I am not going to school today.)", "tidak", ["bukan", "belum", "jangan"]],
 ["Itu ___ kucing, itu anjing. (That is not a cat, that is a dog.)", "bukan", ["tidak", "belum", "jangan"]],
 ["Dia ___ tiba lagi. (He has not arrived yet.)", "belum", ["bukan", "jangan", "ialah"]],
 ["___ lari di dalam kelas! (Don't run in class!)", "Jangan", ["Tidak", "Bukan", "Belum"]],
 ["Air ini ___ sejuk. (This water is not cold.)", "tidak", ["bukan", "jangan", "belum"]],
 ["Ayah saya ___ doktor. (My father is not a doctor.)", "bukan", ["tidak", "belum", "jangan"]],
 ["Kami ___ suka sayur. (We do not like vegetables.)", "tidak", ["bukan", "jangan", "belum"]],
 ["Adik ___ mandi lagi. (My sibling has not bathed yet.)", "belum", ["bukan", "tidak", "jangan"]],
 ["___ makan di sini! (Do not eat here!)", "Jangan", ["Bukan", "Tidak", "Belum"]],
 ["Ini ___ pen saya. (This is not my pen.)", "bukan", ["tidak", "jangan", "belum"]],
 ["Which word do you use before a NOUN to say 'not'?", "bukan", ["tidak", "belum", "jangan"]],
 ["Which word means 'not yet'?", "belum", ["tidak", "bukan", "jangan"]],
 ["Saya ___ mahu teh. (I do not want tea.)", "tidak", ["bukan", "belum", "jangan"]],
 ["Dia ___ pelajar, dia guru. (He is not a student; he is a teacher.)", "bukan", ["tidak", "jangan", "belum"]],
 ["___ bising, bayi sedang tidur! (Don't be noisy, the baby is sleeping!)", "Jangan", ["Bukan", "Tidak", "Belum"]],
 ["Hari ini ___ hari Sabtu. (Today is not Saturday.)", "bukan", ["tidak", "jangan", "belum"]],
 ["Kereta itu ___ mahal. (That car is not expensive.)", "tidak", ["bukan", "jangan", "belum"]],
 ["Kerja rumah saya ___ siap. (My homework is not finished yet.)", "belum", ["bukan", "jangan", "ialah"]],
 ["Which is correct: 'I am not tired.'?", "Saya tidak penat.", ["Saya bukan penat.", "Saya jangan penat.", "Saya belum ialah penat."]],
 ["Which is correct: 'It is not a book.'?", "Ia bukan buku.", ["Ia tidak buku.", "Ia jangan buku.", "Ia belum buku."]]
],
G4: [
 ["Semalam saya ___ pergi ke pasar. (Yesterday I went to the market.)", "sudah", ["akan", "sedang", "belum"]],
 ["Esok kami ___ melawat nenek. (Tomorrow we will visit Grandma.)", "akan", ["sudah", "sedang", "belum"]],
 ["Sekarang dia ___ membaca buku. (Now he is reading a book.)", "sedang", ["akan", "sudah", "belum"]],
 ["Ibu ___ balik dari pejabat. (Mum has already come home from the office.)", "sudah", ["akan", "sedang", "belum"]],
 ["Kapal terbang ___ tiba pada pukul lima. (The plane will arrive at five o'clock.)", "akan", ["sudah", "sedang", "belum"]],
 ["Kami ___ makan malam sekarang. (We are having dinner right now.)", "sedang", ["akan", "sudah", "belum"]],
 ["Awak ___ siap membuat kerja rumah? (Have you already finished your homework?)", "sudah", ["akan", "sedang", "bukan"]],
 ["Saya ___ makan kerana saya baru bangun. (I have not eaten yet.)", "belum", ["sudah", "akan", "sedang"]],
 ["Which word tells us something is happening NOW?", "sedang", ["sudah", "akan", "belum"]],
 ["Which word tells us something has already happened?", "sudah", ["sedang", "akan", "bukan"]],
 ["Tahun depan saya ___ belajar di sekolah baharu. (Next year I will study at a new school.)", "akan", ["sudah", "sedang", "belum"]],
 ["Does the Malay verb 'makan' change for past, present or future?", "No – we add a time word", ["Yes – add -ed", "Yes – add -ing", "Yes – it changes completely"]],
 ["Sekarang hujan ___ turun. (It is raining right now.)", "sedang", ["akan", "sudah", "belum"]],
 ["Minggu lalu kami ___ pergi ke pantai. (Last week we went to the beach.)", "sudah", ["akan", "sedang", "belum"]],
 ["Filem itu ___ bermula. (The film has not started yet.)", "belum", ["sudah", "sedang", "akan"]],
 ["Dia ___ berjumpa doktor pada hari Jumaat. (He will see the doctor on Friday.)", "akan", ["sudah", "sedang", "belum"]],
 ["Sekarang adik ___ tidur di dalam bilik. (Right now my sibling is sleeping in the room.)", "sedang", ["akan", "sudah", "belum"]],
 ["Which time word goes best with 'akan'?", "esok", ["semalam", "tahun lalu", "minggu lalu"]],
 ["Which time word goes best with 'sudah'?", "semalam", ["esok", "minggu depan", "tahun depan"]],
 ["Saya ___ mandi, jadi saya bersih. (I have already bathed, so I am clean.)", "sudah", ["akan", "sedang", "belum"]]
]
});
