/* Extra grammar quiz questions, part 3 (G9–G12) */
window.BAHASA_MORE = window.BAHASA_MORE || {};
Object.assign(window.BAHASA_MORE, {
G9: [
 ["How do you say 'my bag'?", "beg saya", ["saya beg", "beg ialah saya", "beg untuk saya itu"]],
 ["How do you say 'your book' (friendly)?", "buku awak", ["awak buku", "buku ialah awak", "ialah awak buku"]],
 ["How do you say 'his / her house'?", "rumahnya", ["nyarumah", "dia rumah", "rumah ialah dia"]],
 ["How do you say 'Mum's phone'?", "telefon ibu", ["ibu telefon", "telefon untuk ibu ialah", "ialah ibu telefon"]],
 ["How do you say 'our school' (not including you)?", "sekolah kami", ["sekolah mereka", "kami sekolah", "sekolah dia"]],
 ["How do you say 'their car'?", "kereta mereka", ["mereka kereta", "kereta kami", "kereta saya"]],
 ["How do you say 'the teacher's pen'?", "pen cikgu", ["cikgu pen", "pen ialah cikgu", "pen di cikgu"]],
 ["'Namanya Ali' means…", "His / her name is Ali.", ["My name is Ali.", "Their name is Ali.", "Ali is a name."]],
 ["Ini rumah ___. (This is our house – you included.)", "kita", ["mereka", "dia", "saya"]],
 ["___ berwarna biru. (Her bicycle is blue.)", "Basikalnya", ["Nya basikal", "Basikal ialah", "Dia basikal"]],
 ["In Malay, the owner comes…", "after the thing owned", ["before the thing owned", "instead of the thing owned", "in the middle of the word"]],
 ["Kucing ___ sangat comel. (My cat is very cute.)", "saya", ["ialah", "bukan", "tidak"]],
 ["'-nya' can mean…", "his / her / its", ["I / me", "we / us", "they"]],
 ["'Kereta ayah' means…", "Dad's car", ["Dad is a car", "Dad has many cars", "Cars for Dad"]],
 ["___ terbuka. (Its door is open.)", "Pintunya", ["Nya pintu", "Pintu ialah", "Dia pintu"]],
 ["How do you say 'my sister's room'?", "bilik kakak saya", ["kakak bilik saya", "saya bilik kakak", "bilik saya kakak"]],
 ["Ini buku ___. (This is their book.)", "mereka", ["kami", "kita", "ialah"]],
 ["Rumah ___ di Melaka. (My grandmother's house is in Melaka.)", "nenek saya", ["saya nenek", "nenek ialah saya", "saya ialah nenek"]],
 ["Which word means 'our' when you INCLUDE the listener?", "kita", ["kami", "mereka", "dia"]],
 ["Which is correct: 'Aina's book'?", "buku Aina", ["Aina buku", "buku ialah Aina", "Aina punya ialah buku"]]
],
G10: [
 ["Saya suka ayam ___ ikan. (chicken and fish)", "dan", ["atau", "tetapi", "kerana"]],
 ["Awak mahu nasi ___ roti? (rice or bread?)", "atau", ["dan", "kerana", "sambil"]],
 ["Saya lapar ___ belum makan. (because I have not eaten)", "kerana", ["tetapi", "atau", "walaupun"]],
 ["Ali pandai ___ malas. (Ali is clever but lazy.)", "tetapi", ["dan", "kerana", "supaya"]],
 ["Dia menyanyi ___ menari. (She sings while dancing.)", "sambil", ["atau", "kerana", "kecuali"]],
 ["___ dia sakit, dia pergi ke sekolah. (Although he is ill, he goes to school.)", "Walaupun", ["Kerana", "Supaya", "Atau"]],
 ["Semua orang datang ___ Ahmad. (Everyone came except Ahmad.)", "kecuali", ["dan", "atau", "supaya"]],
 ["Saya belajar ___ saya lulus peperiksaan. (so that I pass the exam)", "supaya", ["kecuali", "atau", "tetapi"]],
 ["___ hujan, kami akan berada di rumah. (If it rains, we will stay at home.)", "Jika", ["Walaupun", "Kecuali", "Sambil"]],
 ["Which word means 'because'?", "sebab", ["atau", "tetapi", "sambil"]],
 ["Which word means 'but'?", "tetapi", ["dan", "atau", "sebab"]],
 ["Which word means 'or'?", "atau", ["dan", "tetapi", "jika"]],
 ["Hari ini panas, ___ kami pergi berenang. (so we go swimming)", "jadi", ["tetapi", "atau", "kecuali"]],
 ["Saya makan nasi ___ minum teh. (and drink tea)", "dan", ["tetapi", "walaupun", "supaya"]],
 ["Dia tidak datang ___ dia demam. (because he had a fever)", "kerana", ["sambil", "atau", "dan"]],
 ["Saya mahu membeli buku itu, ___ harganya mahal. (but the price is expensive)", "tetapi", ["dan", "jadi", "supaya"]],
 ["Kami menonton televisyen ___ makan. (while eating)", "sambil", ["tetapi", "jika", "kecuali"]],
 ["Which word means 'although'?", "walaupun", ["kerana", "atau", "jika"]],
 ["Awak boleh pergi ___ awak siapkan kerja rumah. (if you finish your homework)", "jika", ["kecuali", "walaupun", "atau"]],
 ["Ali ___ Aina ialah kawan baik. (Ali and Aina are best friends.)", "dan", ["atau", "tetapi", "kecuali"]]
],
G11: [
 ["Root word 'tulis' becomes…", "menulis", ["bertulis", "mentulis", "menbulis"]],
 ["Root word 'beli' becomes…", "membeli", ["berbeli", "menbeli", "membli"]],
 ["Root word 'dengar' becomes…", "mendengar", ["berdengar", "memdengar", "menengar"]],
 ["Root word 'tonton' becomes…", "menonton", ["bertonton", "mentonton", "memonton"]],
 ["Root word 'lukis' becomes…", "melukis", ["berlukis", "menlukis", "memlukis"]],
 ["Root word 'jalan' becomes… (walk)", "berjalan", ["menjalan", "memjalan", "dijalan"]],
 ["Root word 'main' becomes… (play)", "bermain", ["memain", "menmain", "termain"]],
 ["Root word 'kerja' becomes… (work – a special case!)", "bekerja", ["berkerja", "memkerja", "mengerja"]],
 ["Root word 'renang' becomes… (swim)", "berenang", ["merenang", "berrenang", "menrenang"]],
 ["Root word 'lari' becomes… (run)", "berlari", ["melari", "menlari", "belari"]],
 ["Root word 'masak' becomes…", "memasak", ["bermasak", "menmasak", "menasak"]],
 ["Root word 'baca' becomes…", "membaca", ["berbaca", "menbaca", "mengbaca"]],
 ["Root word 'ajar' becomes… (teach)", "mengajar", ["berajar", "memajar", "menajar"]],
 ["Root word 'ajar' becomes… (study / learn – irregular!)", "belajar", ["berajar", "mengajar", "memajar"]],
 ["Saya ___ novel di perpustakaan. (I read a novel in the library.)", "membaca", ["berjalan", "menonton", "memasak"]],
 ["Ibu ___ nasi di dapur. (Mum cooks rice in the kitchen.)", "memasak", ["berenang", "menulis", "bermain"]],
 ["Kami ___ di kolam. (We swim in the pool.)", "berenang", ["membaca", "menulis", "membeli"]],
 ["Dia ___ surat kepada nenek. (He writes a letter to Grandma.)", "menulis", ["berlari", "berenang", "memasak"]],
 ["Saya ___ baju baharu di kedai. (I buy a new shirt at the shop.)", "membeli", ["berjalan", "bermain", "menonton"]],
 ["Kami ___ muzik di radio. (We listen to music on the radio.)", "mendengar", ["membeli", "berlari", "memasak"]]
],
G12: [
 ["___ masuk. (Please come in.)", "Sila", ["Jangan", "Belum", "Mesti"]],
 ["___ lupa kerja rumah! (Don't forget your homework!)", "Jangan", ["Sila", "Mari", "Boleh"]],
 ["___ kita makan! (Let's eat!)", "Mari", ["Tolong", "Jangan", "Mesti"]],
 ["___ bantu saya. (Please help me.)", "Tolong", ["Sila", "Mari", "Belum"]],
 ["___ saya pinjam pen awak? (May I borrow your pen?)", "Boleh", ["Sila", "Jangan", "Mesti"]],
 ["Kita ___ hormat kepada guru. (We must respect teachers.)", "mesti", ["boleh", "jangan", "sila"]],
 ["___ ambil kek ini. (Please help yourself to this cake.)", "Sila", ["Jangan", "Boleh", "Mesti"]],
 ["___ buang sampah di sini! (Don't throw rubbish here!)", "Jangan", ["Sila", "Mari", "Tolong"]],
 ["Saya ___ bercakap bahasa Melayu. (I can speak Malay.)", "boleh", ["jangan", "sila", "mari"]],
 ["___ tutup tingkap itu. (Please close that window.)", "Tolong", ["Jangan", "Mesti", "Belum"]],
 ["Which word means 'let's'?", "mari", ["sila", "jangan", "mesti"]],
 ["Which word means 'must'?", "mesti", ["boleh", "sila", "mari"]],
 ["Which word means 'can / may'?", "boleh", ["mesti", "jangan", "mari"]],
 ["Which word is a polite INVITATION?", "sila", ["jangan", "mesti", "belum"]],
 ["'Boleh saya keluar?' means…", "May I go out?", ["Please go out.", "Do not go out.", "Let us go out."]],
 ["'Jangan lari!' means…", "Don't run!", ["Please run.", "Let's run.", "I can run."]],
 ["'Mari kita belajar!' means…", "Let's study!", ["We must study.", "Don't study.", "I can study."]],
 ["___ saya minta air? (Can I have some water?)", "Boleh", ["Jangan", "Mari", "Mesti"]],
 ["___ duduk di sini, Puan. (Please sit here, madam.)", "Sila", ["Jangan", "Mesti", "Belum"]],
 ["Semua murid ___ memakai uniform. (All pupils must wear uniform.)", "mesti", ["jangan", "sila", "mari"]]
]
});
