/* Extra grammar quiz questions, part 2 (G5–G8) */
window.BAHASA_MORE = window.BAHASA_MORE || {};
Object.assign(window.BAHASA_MORE, {
G5: [
 ["Ada tiga ___ budak di taman. (three children in the park)", "orang", ["ekor", "buah", "helai"]],
 ["Kami ada empat ___ ayam. (four chickens)", "ekor", ["orang", "biji", "helai"]],
 ["Ibu membeli lima ___ epal. (five apples)", "biji", ["orang", "ekor", "helai"]],
 ["Dia menulis dengan sebatang ___. (a pen)", "pen", ["baju", "kucing", "kereta"]],
 ["Saya ada dua ___ buku. (two books)", "buah", ["orang", "ekor", "helai"]],
 ["Ayah membeli sebuah ___. (a car)", "kereta", ["telur", "kucing", "pokok"]],
 ["Pak cik menanam tiga ___ pokok. (three trees)", "batang", ["ekor", "orang", "helai"]],
 ["Saya perlukan dua ___ kertas. (two sheets of paper)", "helai", ["ekor", "buah", "orang"]],
 ["Which classifier is used for people?", "orang", ["ekor", "biji", "buah"]],
 ["Which classifier is used for animals?", "ekor", ["orang", "helai", "batang"]],
 ["'Seorang' means…", "one person", ["one animal", "one house", "one egg"]],
 ["'Seekor kucing' means…", "one cat", ["one person", "one book", "one egg"]],
 ["Nenek mempunyai enam ___ cucu. (six grandchildren)", "orang", ["ekor", "biji", "buah"]],
 ["Kami tinggal di sebuah ___. (a house)", "rumah", ["telur", "baju", "ikan"]],
 ["Adik makan tiga ___ telur. (three eggs)", "biji", ["ekor", "orang", "helai"]],
 ["Saya membeli dua ___ baju. (two shirts)", "helai", ["ekor", "orang", "biji"]],
 ["What does 'beberapa' mean?", "several / some", ["one", "none", "every"]],
 ["Nelayan itu menangkap sepuluh ___ ikan. (ten fish)", "ekor", ["orang", "biji", "helai"]],
 ["Which noun goes with 'sebiji'?", "epal", ["kucing", "murid", "baju"]],
 ["Ada tiga ___ sekolah di bandar ini. (three schools in this town)", "buah", ["orang", "ekor", "biji"]]
],
G6: [
 ["___ awak pergi ke sekolah? (How do you go to school?)", "Bagaimana", ["Siapa", "Bila", "Berapa"]],
 ["___ hari lahir awak? (When is your birthday?)", "Bila", ["Siapa", "Kenapa", "Berapa"]],
 ["___ orang ada dalam keluarga awak? (How many people are in your family?)", "Berapa", ["Siapa", "Bila", "Apa"]],
 ["___ awak pergi semalam? (Where did you go yesterday?)", "Ke mana", ["Di mana", "Dari mana", "Siapa"]],
 ["Awak berasal ___? (Where are you from?)", "dari mana", ["ke mana", "di mana", "bila"]],
 ["___ guru bahasa Melayu awak? (Who is your Malay teacher?)", "Siapa", ["Apa", "Bila", "Berapa"]],
 ["___ kamu sedih? (Why are you sad?)", "Kenapa", ["Siapa", "Berapa", "Bila"]],
 ["Which question word means 'which one'?", "yang mana", ["di mana", "bagaimana", "bila"]],
 ["Ini ___? (What is this?)", "apa", ["siapa", "bila", "berapa"]],
 ["___ umur adik awak? (How old is your younger sibling?)", "Berapa", ["Siapa", "Bila", "Kenapa"]],
 ["'Kenapa' means…", "why", ["when", "who", "where"]],
 ["'Berapa' means…", "how many / how much", ["why", "who", "where"]],
 ["___ awak tinggal? (Where do you live?)", "Di mana", ["Ke mana", "Siapa", "Bila"]],
 ["Answer: 'Sebab saya sakit.' Which question?", "Kenapa awak tidak datang?", ["Bila awak datang?", "Siapa awak?", "Berapa awak datang?"]],
 ["Answer: 'Pada hari Isnin.' Which question?", "Bila awak pergi?", ["Siapa awak?", "Apa itu?", "Di mana rumah awak?"]],
 ["Answer: 'Sepuluh ringgit.' Which question?", "Berapa harga buku ini?", ["Siapa penulis buku ini?", "Bila buku ini tiba?", "Di mana buku ini?"]],
 ["Answer: 'Saya pergi ke perpustakaan.' Which question?", "Awak pergi ke mana?", ["Awak dari mana?", "Awak siapa?", "Awak bila?"]],
 ["Answer: 'Nama saya Haris.' Which question?", "Siapa nama awak?", ["Berapa nama awak?", "Kenapa nama awak?", "Bila nama awak?"]],
 ["___ awak buat hari ini? (What did you do today?)", "Apa", ["Siapa", "Bila", "Berapa"]],
 ["Dia datang dengan ___? (Who did he come with?)", "siapa", ["apa", "berapa", "bila"]]
],
G7: [
 ["Kami tinggal ___ Kuala Lumpur. (in Kuala Lumpur)", "di", ["ke", "dari", "pada"]],
 ["Ali pergi ___ pasar. (Ali goes to the market.)", "ke", ["di", "dari", "untuk"]],
 ["Nenek datang ___ kampung. (Grandma comes from the village.)", "dari", ["ke", "di", "untuk"]],
 ["Surat ini ___ cikgu. (This letter is for the teacher.)", "untuk", ["dari", "di", "pada"]],
 ["Saya menulis kad ___ kawan saya. (I write a card to my friend.)", "kepada", ["di", "dari", "pada"]],
 ["Dia pergi ke sekolah ___ basikal. (by bicycle)", "dengan", ["pada", "di", "kepada"]],
 ["Kelas bermula ___ pukul lapan. (at eight o'clock)", "pada", ["di", "ke", "dengan"]],
 ["Saya makan nasi ___ sudu. (with a spoon)", "dengan", ["pada", "ke", "dari"]],
 ["Buku itu ada ___ atas meja. (on the table)", "di", ["ke", "dari", "untuk"]],
 ["Hadiah ini ___ awak. (This gift is for you.)", "untuk", ["di", "dari", "pada"]],
 ["Ali lebih tinggi ___ Ahmad. (Ali is taller than Ahmad.)", "daripada", ["kepada", "dengan", "di"]],
 ["Kami bertemu ___ hari Rabu. (on Wednesday)", "pada", ["di", "ke", "dengan"]],
 ["Ibu memberi wang ___ adik. (Mum gave money to my sibling.)", "kepada", ["di", "dari", "pada"]],
 ["Saya menerima hadiah ___ ayah. (I received a present from Dad.)", "daripada", ["ke", "di", "untuk"]],
 ["Which preposition is used with a PLACE you are going to?", "ke", ["pada", "kepada", "daripada"]],
 ["Which preposition is used with a PERSON you give something to?", "kepada", ["ke", "di", "dari"]],
 ["Bas itu datang ___ bandar. (The bus comes from the town.)", "dari", ["ke", "di", "pada"]],
 ["Saya berjalan ___ rumah ke sekolah. (I walk from home to school.)", "dari", ["di", "pada", "dengan"]],
 ["Kucing itu tidur ___ bawah kerusi. (under the chair)", "di", ["ke", "dari", "pada"]],
 ["Kami pergi ke London ___ kapal terbang. (by aeroplane)", "dengan", ["pada", "di", "kepada"]]
],
G8: [
 ["Kereta ini ___ mahal daripada kereta itu. (more expensive)", "lebih", ["paling", "sangat", "setinggi"]],
 ["Gunung itu ___ tinggi. (very tall)", "sangat", ["lebih", "paling", "daripada"]],
 ["Dia ialah murid yang ___ rajin. (the most diligent)", "paling", ["lebih", "sangat", "kurang"]],
 ["Kakak lebih rajin ___ abang. (more diligent than my brother)", "daripada", ["dengan", "untuk", "pada"]],
 ["Which means 'a big house'?", "rumah besar", ["besar rumah", "ialah besar rumah", "rumah ialah besar"]],
 ["Which means 'a blue shirt'?", "baju biru", ["biru baju", "baju ialah biru", "sangat baju biru"]],
 ["Ujian ini ___ mudah daripada ujian semalam. (easier)", "lebih", ["sangat", "paling", "amat"]],
 ["Which word means 'most (the -est)'?", "paling", ["lebih", "kurang", "sangat"]],
 ["Which word means 'more'?", "lebih", ["paling", "kurang", "sangat"]],
 ["Which word means 'less'?", "kurang", ["lebih", "paling", "sangat"]],
 ["Bilik saya ___ kecil daripada bilik abang. (smaller)", "lebih", ["paling", "sangat", "ialah"]],
 ["Air ini ___ sejuk. (very cold)", "amat", ["lebih", "paling", "daripada"]],
 ["Dia berlari ___ cepat dalam kelas. (the fastest)", "paling", ["lebih", "kurang", "daripada"]],
 ["Ali ___ Ahmad. (Ali is as tall as Ahmad.)", "setinggi", ["lebih tinggi", "paling tinggi", "tidak tinggi"]],
 ["Which is correct: 'the tallest pupil'?", "murid yang paling tinggi", ["paling murid tinggi", "murid tinggi paling", "tinggi paling murid"]],
 ["Cuaca hari ini ___ panas daripada semalam. (hotter)", "lebih", ["paling", "sangat", "ialah"]],
 ["Buku ini ___ menarik. (This book is very interesting.)", "sangat", ["daripada", "lebih daripada", "kurang daripada"]],
 ["Ibu memasak makanan yang ___ sedap di dunia. (the most delicious in the world)", "paling", ["lebih", "kurang", "sangat"]],
 ["Adik ___ tinggi daripada saya. (My sibling is less tall than me.)", "kurang", ["paling", "sangat", "lebih"]],
 ["Where do adjectives go in Malay?", "After the noun", ["Before the noun", "At the end of a sentence only", "Before the verb"]]
]
});
